### ISSUE TITLE
진태영님 개인 프로젝트 멘토링 offline 5, 2024-09-12

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/Activity#459]
오후 6시 30분
딥파인 회의실

**Comment by jongfeel** [comment]
## 논의내용

- Github issue에 대한 이해
- 진행한 내용에 대해 조금씩 진행하고 피드백 받기를 더 활용: 
  - 찾아보고 확신을 가진 내용을 가지고 리뷰하는 방식으로 진행 => 플러터 같이 봐주는 분과 대화 필요
- 시간 관리에 대한 인지 필요, 뽀모도로 같은 기법을 사용해 보면 좋다.
- 성과, 결과 내는 방법: 동작하는 코드를 작성해서 실행이 된다.

**Comment by jintaeyeong** [comment]
감사합니다 ^^ 😄👍
